### ISSUE TITLE
[Approved] Debate about the future of mod CME (development was abandoned)

### ISSUE THREAD

**Issue by diogo-gomes** [BlockMen/cme#12]
# This issue is to debate about the future of this mod because the development was abandoned.
### Approved and cloned unforked: https://github.com/minetest-mods/mob-engine

----------

I made a request to incorporate this mod in @minetest-mods team and the response of @sofar was:

> ... if I get a response from several fork maintainers that they want to collaboratively maintain this code, then I'd be willing to accept,
> ###### (see the full request [here](https://github.com/minetest-mods/minetest-mods.github.io/issues/22))

---

The main question is:
## \- Do you agree with the incorporation of my fork (**[mob-engine](https://github.com/diogo-gomes/mob-engine)**) in the team @minetest-mods?

Other questions:
### \- Do you want incorporate another fork instead?

---
#### You can simple answer _I agree_ or formulate your opinion.

---

---
## Answers

| Total | 6 | Total | 6 |
| --- | --: | --- | --: |
| Agree | 5 | Maintain | 4 |
| Not agree | 0 | Not maintain | 2 |
| Neutral | 1 | Neutral | 0 |

---
### Author
@BlockMen: not contacted yet

### Forkers
@Athemis: not contacted yet
@diogo-gomes: agree / maintain
@ExcaliburZero: agree / not maintain
@jalami: not contacted yet
@LotekHeavy: not contacted yet
@mahmutelmas06: agree / maintain
@RiZom-91: not contacted yet

### Contributors
@LNJ2: agree / maintain

### All (developers / users / gamers)
@bbaez: not contacted yet
@BrunoMine: agree / maintain
@ghost: not contacted yet
@JurajVajda: not contacted yet
@Rogier-5: neutral / not maintain
@Ugdhar: not contacted yet
@Ziusudra: not contacted yet

**Comment by ExcaliburZero** [comment]
I agree. However, unfortunately I wouldn't be able to help maintain it.

**Comment by BrunoMine** [comment]
I agree. And I'm willing to collaborate testing and sending some basic corrections.

**Comment by diogo-gomes** [comment]
@ExcaliburZero @BrunoMine, thanks for the feedback.

Please, share this issue with all interested people.

**Comment by LNJ2** [comment]
I also agree! :+1:
I will definitely make pull requests for all my I changes I made in my subgame.
Maintain: Yes!
**_:)_**

**Comment by diogo-gomes** [comment]
@LNJ2, thanks for your answer.

Good point about reference "forked from". :+1: 
I think it's not easy, I need remove origin, create new repository, etc. If minetest-team accept my fork, I remove the reference there, if not accepted, I remove reference in mine.

**Please, share this debate with other people.** Thanks!

**Comment by Rogier-5** [comment]
I'm impartial to the matter, but I'd like to see the mod being well-maintained in some way. I probably won't contribute, but don't take my word for it :-)

**Comment by LNJ2** [comment]
Why do you changed the licenses to LGPLv3 and CC BY-SA 4.0? This will make it uncompatible with Minetest / MTG. But LGPLv2.1 and CC BY-SA 3.0 would be fine.

**Comment by diogo-gomes** [comment]
@Rogier-5, when you say "imparcial", do you mean "with no opinion"?

---

@LNJ2, when I read the [Minetest Wiki / Licensing](http://wiki.minetest.net/Licensing), 
I assumed that we can choose a posterior version of LGPL:

> The LGPL 2.1+ free software license, under which Minetest is distributed does allow implicit distribution of the compiled game, and subsequent modifications that are distributed by default.

And in develop wiki:

> Collaboration is encouraged. To let this happen:
Have a non-restrictive license ("no commercial use" or "no derivative work" clauses should be avoided).

Can you explain how it's incompatible?
(I'll change the license if necessary)

**Comment by LNJ2** [comment]
@diogo-gomes You can use LGPLv2.1**+** in a LGPLv3(+) project and use it as LGPLv3. But you can't use LGPLv3(+) code in a LGPLv2.1+ project! If you say that your project is LGPLv3 or later, you can't use it as LGPLv2.1 (only LGPLv4). So you would have to add "or LGPLv2.1 or any later version", but that is LGPLv2.1+ again.
So if you choose LGPLv3+, this mob api will only be compatible with MTG, when they change their license to LGPLv3(+).

**Comment by Rogier-5** [comment]
IANAL, but IMO the minetest api is public, so it can be used by any mod, just like the linux kernel can be used by any program.

As cme is a modpack, I think that even every mod in the pack could have a different license, as long as it sticks to the public api of the creatures mod.

However, if somebody wants to add code to cme, or to one of the animals, that is copied from another location, e.g. because that code uses an interesting fighting implementation, then that code and the mod it is added to need to be license-compatible.

So if you might ever want to incorporate code originally written for another mod, with a different license, your license would have to be compatible with that mod's license. So your choice of license can / will also limit what you are able to do with the code in the future.

@diogo-gomes I saw you removed the original license file. However, the license file expressly forbids that ! Again, IANAL, but unless you have explicit permission from @BlockMen, I'd keep the original file, but document that all future contributions will be licensed with the new license. And of course, you must be certain that the new license and BlockMen's license are compatible !

**Comment by diogo-gomes** [comment]
Okay, I understand about Minetest license.
I license LGPLv3 because is a modpack but if the future of this is integration with game or other mods, of course I change :) 

@LNJ2 , about git, I use gitflow ([link](http://nvie.com/posts/a-successful-git-branching-model/),[link](https://github.com/nvie/gitflow)) and [senver 2.0.0](http://semver.org/) and commits you mention are automatic. (I use that in all my professional projects because perhaps will be a standard in a near future...)

@Rogier-5 , I don't remove the licence, I improve the extension to markdown. In [LICENSE.md](https://github.com/diogo-gomes/mob-engine/blob/master/LICENSE.md) you can see all licenses in an organised way.

**Comment by LNJ2** [comment]
@Rogier-5 You can even change the licenses for some lines of code, if the licenses are compatible (e.g. some lines of WTFPL code in file that is licensed under GPLv3). :D

**Comment by LNJ2** [comment]
@diogo-gomes Better just use the command line. (GUIs are something for windows users)

**Comment by diogo-gomes** [comment]
git-flow is cli, lol. I don't use windows.

Ex:
git flow feature start "example"
git flow feature finish "example" (and this branch is merged in develop)
git flow release start
.....
etc
git flow release finish
and release are merged, tag created, version created in one command...

**Comment by Rogier-5** [comment]
@diogo-gomes impartial = neutral.

As I don't intend to contribute (although I may still do if I run into a bug that I want removed), I don't think I should have a say. And in the end, all depends on the direction things take, and I don't know that in advance anyway.

Re: license removal: OK, I missed that.

**Comment by Rogier-5** [comment]
> if the future of this is integration with game or other mods, of course I change :) 

Do realize that if you want to change the license in the future, either you'd have to get permission from all contributors, or the new license would have to be compatible with the one you're choosing now, which, I get the impression, is not very likely if you choose (L)GPL3.

**Comment by diogo-gomes** [comment]
# To all:

I reversed everything and will only publish code after a decision.
I think there are a few volunteers to keep the active mob and I will wait for integration in minetest-mods and I'll make the changes later.

**Comment by LNJ2** [comment]
@diogo-gomes ups.. (I didn't even opened the links, sorry)

senver 2.0.0 is nice (and I also use it, in some of my project [not TNG]) :)

And I also like this workflow (and I just use a bit simpler version, without release branches) http://nvie.com/posts/a-successful-git-branching-model/

And this git-flow extension also seems cool, but I'm sure you can configure it so that it won't add merge commits (just uses git rebase and git pull)

**Comment by mahmutelmas06** [comment]
I do agree too.

I will try to improve it in my spare times

**Comment by LNJ2** [comment]
(I still do not agree with LGPLv3+, I want LGPLv2.1+ as Minetest and no merge commits)

**Comment by diogo-gomes** [comment]
@mahmutelmas06, thank you for your answer.

@LNJ2, I revert everything. **Current licenses are the originals**.

**Comment by BrunoMine** [comment]
What is our verdict?

**Comment by diogo-gomes** [comment]
## The maintainers names were proposed.

**Comment by diogo-gomes** [comment]
# Approved and cloned unforked: https://github.com/minetest-mods/mob-engine

**Comment by sofar** [comment]
You should close this.
